//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBibliotheque.ServiceReferenceBibliotheque {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class Utilisateur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] PretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_naisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> derniereconnexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string motdepasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusCompteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] Pret {
            get {
                return this.PretField;
            }
            set {
                if ((object.ReferenceEquals(this.PretField, value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_nais {
            get {
                return this.date_naisField;
            }
            set {
                if ((this.date_naisField.Equals(value) != true)) {
                    this.date_naisField = value;
                    this.RaisePropertyChanged("date_nais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> derniereconnexion {
            get {
                return this.derniereconnexionField;
            }
            set {
                if ((this.derniereconnexionField.Equals(value) != true)) {
                    this.derniereconnexionField = value;
                    this.RaisePropertyChanged("derniereconnexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motdepasse {
            get {
                return this.motdepasseField;
            }
            set {
                if ((object.ReferenceEquals(this.motdepasseField, value) != true)) {
                    this.motdepasseField = value;
                    this.RaisePropertyChanged("motdepasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomUser {
            get {
                return this.nomUserField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUserField, value) != true)) {
                    this.nomUserField = value;
                    this.RaisePropertyChanged("nomUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photo {
            get {
                return this.photoField;
            }
            set {
                if ((object.ReferenceEquals(this.photoField, value) != true)) {
                    this.photoField = value;
                    this.RaisePropertyChanged("photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexe {
            get {
                return this.sexeField;
            }
            set {
                if ((object.ReferenceEquals(this.sexeField, value) != true)) {
                    this.sexeField = value;
                    this.RaisePropertyChanged("sexe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusCompte {
            get {
                return this.statusCompteField;
            }
            set {
                if ((object.ReferenceEquals(this.statusCompteField, value) != true)) {
                    this.statusCompteField = value;
                    this.RaisePropertyChanged("statusCompte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeUser {
            get {
                return this.typeUserField;
            }
            set {
                if ((object.ReferenceEquals(this.typeUserField, value) != true)) {
                    this.typeUserField = value;
                    this.RaisePropertyChanged("typeUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pret", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class Pret : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Livre LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur UtilisateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datedebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datefinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> livreidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Livre Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((object.ReferenceEquals(this.LivreField, value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur Utilisateur {
            get {
                return this.UtilisateurField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilisateurField, value) != true)) {
                    this.UtilisateurField = value;
                    this.RaisePropertyChanged("Utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datedebut {
            get {
                return this.datedebutField;
            }
            set {
                if ((this.datedebutField.Equals(value) != true)) {
                    this.datedebutField = value;
                    this.RaisePropertyChanged("datedebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datefin {
            get {
                return this.datefinField;
            }
            set {
                if ((this.datefinField.Equals(value) != true)) {
                    this.datefinField = value;
                    this.RaisePropertyChanged("datefin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> livreid {
            get {
                return this.livreidField;
            }
            set {
                if ((this.livreidField.Equals(value) != true)) {
                    this.livreidField = value;
                    this.RaisePropertyChanged("livreid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Livre", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class Livre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Auteur AuteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Categorie CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] PretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> auteuridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> categorieidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Auteur Auteur {
            get {
                return this.AuteurField;
            }
            set {
                if ((object.ReferenceEquals(this.AuteurField, value) != true)) {
                    this.AuteurField = value;
                    this.RaisePropertyChanged("Auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Categorie Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] Pret {
            get {
                return this.PretField;
            }
            set {
                if ((object.ReferenceEquals(this.PretField, value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> auteurid {
            get {
                return this.auteuridField;
            }
            set {
                if ((this.auteuridField.Equals(value) != true)) {
                    this.auteuridField = value;
                    this.RaisePropertyChanged("auteurid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> categorieid {
            get {
                return this.categorieidField;
            }
            set {
                if ((this.categorieidField.Equals(value) != true)) {
                    this.categorieidField = value;
                    this.RaisePropertyChanged("categorieid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resume {
            get {
                return this.resumeField;
            }
            set {
                if ((object.ReferenceEquals(this.resumeField, value) != true)) {
                    this.resumeField = value;
                    this.RaisePropertyChanged("resume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auteur", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class Auteur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Livre[] LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aproposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_naisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nationaliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeAuteurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Livre[] Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((object.ReferenceEquals(this.LivreField, value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apropos {
            get {
                return this.aproposField;
            }
            set {
                if ((object.ReferenceEquals(this.aproposField, value) != true)) {
                    this.aproposField = value;
                    this.RaisePropertyChanged("apropos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_nais {
            get {
                return this.date_naisField;
            }
            set {
                if ((this.date_naisField.Equals(value) != true)) {
                    this.date_naisField = value;
                    this.RaisePropertyChanged("date_nais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalite {
            get {
                return this.nationaliteField;
            }
            set {
                if ((object.ReferenceEquals(this.nationaliteField, value) != true)) {
                    this.nationaliteField = value;
                    this.RaisePropertyChanged("nationalite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photo {
            get {
                return this.photoField;
            }
            set {
                if ((object.ReferenceEquals(this.photoField, value) != true)) {
                    this.photoField = value;
                    this.RaisePropertyChanged("photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexe {
            get {
                return this.sexeField;
            }
            set {
                if ((object.ReferenceEquals(this.sexeField, value) != true)) {
                    this.sexeField = value;
                    this.RaisePropertyChanged("sexe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeAuteur {
            get {
                return this.typeAuteurField;
            }
            set {
                if ((object.ReferenceEquals(this.typeAuteurField, value) != true)) {
                    this.typeAuteurField = value;
                    this.RaisePropertyChanged("typeAuteur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorie", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class Categorie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBibliotheque.ServiceReferenceBibliotheque.Livre[] LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBibliotheque.ServiceReferenceBibliotheque.Livre[] Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((object.ReferenceEquals(this.LivreField, value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="livreDeails", Namespace="http://schemas.datacontract.org/2004/07/ServiceBibliotheque")]
    [System.SerializableAttribute()]
    public partial class livreDeails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int auteuridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categorieidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string auteur {
            get {
                return this.auteurField;
            }
            set {
                if ((object.ReferenceEquals(this.auteurField, value) != true)) {
                    this.auteurField = value;
                    this.RaisePropertyChanged("auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int auteurid {
            get {
                return this.auteuridField;
            }
            set {
                if ((this.auteuridField.Equals(value) != true)) {
                    this.auteuridField = value;
                    this.RaisePropertyChanged("auteurid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categorie {
            get {
                return this.categorieField;
            }
            set {
                if ((object.ReferenceEquals(this.categorieField, value) != true)) {
                    this.categorieField = value;
                    this.RaisePropertyChanged("categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categorieid {
            get {
                return this.categorieidField;
            }
            set {
                if ((this.categorieidField.Equals(value) != true)) {
                    this.categorieidField = value;
                    this.RaisePropertyChanged("categorieid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resume {
            get {
                return this.resumeField;
            }
            set {
                if ((object.ReferenceEquals(this.resumeField, value) != true)) {
                    this.resumeField = value;
                    this.RaisePropertyChanged("resume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titre {
            get {
                return this.titreField;
            }
            set {
                if ((object.ReferenceEquals(this.titreField, value) != true)) {
                    this.titreField = value;
                    this.RaisePropertyChanged("titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBibliotheque.IServiceBibliotheque")]
    public interface IServiceBibliotheque {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/s_inscrire", ReplyAction="http://tempuri.org/IServiceBibliotheque/s_inscrireResponse")]
        void s_inscrire(ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/s_inscrire", ReplyAction="http://tempuri.org/IServiceBibliotheque/s_inscrireResponse")]
        System.Threading.Tasks.Task s_inscrireAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/addAuteurResponse")]
        void addAuteur(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/addAuteurResponse")]
        System.Threading.Tasks.Task addAuteurAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateAuteurResponse")]
        void updateAuteur(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateAuteurResponse")]
        System.Threading.Tasks.Task updateAuteurAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteAuteurResponse")]
        void deleteAuteur(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteAuteurResponse")]
        System.Threading.Tasks.Task deleteAuteurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/addLivreResponse")]
        void addLivre(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/addLivreResponse")]
        System.Threading.Tasks.Task addLivreAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateLivreResponse")]
        void updateLivre(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateLivreResponse")]
        System.Threading.Tasks.Task updateLivreAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteLivreResponse")]
        void deleteLivre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteLivreResponse")]
        System.Threading.Tasks.Task deleteLivreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/addCategorieResponse")]
        void addCategorie(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/addCategorieResponse")]
        System.Threading.Tasks.Task addCategorieAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateCategorieResponse")]
        void updateCategorie(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateCategorieResponse")]
        System.Threading.Tasks.Task updateCategorieAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteCategorieResponse")]
        void deleteCategorie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deleteCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/deleteCategorieResponse")]
        System.Threading.Tasks.Task deleteCategorieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/nomvreLivreCategori", ReplyAction="http://tempuri.org/IServiceBibliotheque/nomvreLivreCategoriResponse")]
        int nomvreLivreCategori(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/nomvreLivreCategori", ReplyAction="http://tempuri.org/IServiceBibliotheque/nomvreLivreCategoriResponse")]
        System.Threading.Tasks.Task<int> nomvreLivreCategoriAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addPret", ReplyAction="http://tempuri.org/IServiceBibliotheque/addPretResponse")]
        void addPret(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/addPret", ReplyAction="http://tempuri.org/IServiceBibliotheque/addPretResponse")]
        System.Threading.Tasks.Task addPretAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updatePret", ReplyAction="http://tempuri.org/IServiceBibliotheque/updatePretResponse")]
        void updatePret(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updatePret", ReplyAction="http://tempuri.org/IServiceBibliotheque/updatePretResponse")]
        System.Threading.Tasks.Task updatePretAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deletePret", ReplyAction="http://tempuri.org/IServiceBibliotheque/deletePretResponse")]
        void deletePret(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/deletePret", ReplyAction="http://tempuri.org/IServiceBibliotheque/deletePretResponse")]
        System.Threading.Tasks.Task deletePretAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getUser", ReplyAction="http://tempuri.org/IServiceBibliotheque/getUserResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur getUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getUser", ReplyAction="http://tempuri.org/IServiceBibliotheque/getUserResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur> getUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getUsers", ReplyAction="http://tempuri.org/IServiceBibliotheque/getUsersResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getUsers", ReplyAction="http://tempuri.org/IServiceBibliotheque/getUsersResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur[]> getUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getCategories", ReplyAction="http://tempuri.org/IServiceBibliotheque/getCategoriesResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Categorie[] getCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getCategories", ReplyAction="http://tempuri.org/IServiceBibliotheque/getCategoriesResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Categorie[]> getCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivres", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivres", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivresByCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresByCategorieResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivresByCategorie(int categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivresByCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresByCategorieResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresByCategorieAsync(int categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivresByAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresByAuteurResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivresByAuteur(int auteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivresByAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivresByAuteurResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresByAuteurAsync(int auteur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getDetailsLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/getDetailsLivreResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Livre getDetailsLivre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getDetailsLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/getDetailsLivreResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Livre> getDetailsLivreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getPrets", ReplyAction="http://tempuri.org/IServiceBibliotheque/getPretsResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] getPrets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getPrets", ReplyAction="http://tempuri.org/IServiceBibliotheque/getPretsResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Pret[]> getPretsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getAuteurs", ReplyAction="http://tempuri.org/IServiceBibliotheque/getAuteursResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Auteur[] getAuteurs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getAuteurs", ReplyAction="http://tempuri.org/IServiceBibliotheque/getAuteursResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Auteur[]> getAuteursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/getAuteurResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Auteur getAuteur(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getAuteur", ReplyAction="http://tempuri.org/IServiceBibliotheque/getAuteurResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Auteur> getAuteurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/getCategorieResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Categorie getCategorie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getCategorie", ReplyAction="http://tempuri.org/IServiceBibliotheque/getCategorieResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Categorie> getCategorieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivreResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Livre getLivre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getLivre", ReplyAction="http://tempuri.org/IServiceBibliotheque/getLivreResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Livre> getLivreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getPret", ReplyAction="http://tempuri.org/IServiceBibliotheque/getPretResponse")]
        ClientBibliotheque.ServiceReferenceBibliotheque.Pret getPret(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/getPret", ReplyAction="http://tempuri.org/IServiceBibliotheque/getPretResponse")]
        System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Pret> getPretAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateRoleUser", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateRoleUserResponse")]
        void updateRoleUser(int id, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBibliotheque/updateRoleUser", ReplyAction="http://tempuri.org/IServiceBibliotheque/updateRoleUserResponse")]
        System.Threading.Tasks.Task updateRoleUserAsync(int id, string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBibliothequeChannel : ClientBibliotheque.ServiceReferenceBibliotheque.IServiceBibliotheque, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBibliothequeClient : System.ServiceModel.ClientBase<ClientBibliotheque.ServiceReferenceBibliotheque.IServiceBibliotheque>, ClientBibliotheque.ServiceReferenceBibliotheque.IServiceBibliotheque {
        
        public ServiceBibliothequeClient() {
        }
        
        public ServiceBibliothequeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBibliothequeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBibliothequeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBibliothequeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void s_inscrire(ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur user) {
            base.Channel.s_inscrire(user);
        }
        
        public System.Threading.Tasks.Task s_inscrireAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur user) {
            return base.Channel.s_inscrireAsync(user);
        }
        
        public void addAuteur(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur) {
            base.Channel.addAuteur(newAuteur);
        }
        
        public System.Threading.Tasks.Task addAuteurAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur) {
            return base.Channel.addAuteurAsync(newAuteur);
        }
        
        public void updateAuteur(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur) {
            base.Channel.updateAuteur(newAuteur);
        }
        
        public System.Threading.Tasks.Task updateAuteurAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Auteur newAuteur) {
            return base.Channel.updateAuteurAsync(newAuteur);
        }
        
        public void deleteAuteur(int id) {
            base.Channel.deleteAuteur(id);
        }
        
        public System.Threading.Tasks.Task deleteAuteurAsync(int id) {
            return base.Channel.deleteAuteurAsync(id);
        }
        
        public void addLivre(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre) {
            base.Channel.addLivre(newLivre);
        }
        
        public System.Threading.Tasks.Task addLivreAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre) {
            return base.Channel.addLivreAsync(newLivre);
        }
        
        public void updateLivre(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre) {
            base.Channel.updateLivre(newLivre);
        }
        
        public System.Threading.Tasks.Task updateLivreAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Livre newLivre) {
            return base.Channel.updateLivreAsync(newLivre);
        }
        
        public void deleteLivre(int id) {
            base.Channel.deleteLivre(id);
        }
        
        public System.Threading.Tasks.Task deleteLivreAsync(int id) {
            return base.Channel.deleteLivreAsync(id);
        }
        
        public void addCategorie(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie) {
            base.Channel.addCategorie(newCategorie);
        }
        
        public System.Threading.Tasks.Task addCategorieAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie) {
            return base.Channel.addCategorieAsync(newCategorie);
        }
        
        public void updateCategorie(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie) {
            base.Channel.updateCategorie(newCategorie);
        }
        
        public System.Threading.Tasks.Task updateCategorieAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Categorie newCategorie) {
            return base.Channel.updateCategorieAsync(newCategorie);
        }
        
        public void deleteCategorie(int id) {
            base.Channel.deleteCategorie(id);
        }
        
        public System.Threading.Tasks.Task deleteCategorieAsync(int id) {
            return base.Channel.deleteCategorieAsync(id);
        }
        
        public int nomvreLivreCategori(int id) {
            return base.Channel.nomvreLivreCategori(id);
        }
        
        public System.Threading.Tasks.Task<int> nomvreLivreCategoriAsync(int id) {
            return base.Channel.nomvreLivreCategoriAsync(id);
        }
        
        public void addPret(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret) {
            base.Channel.addPret(newPret);
        }
        
        public System.Threading.Tasks.Task addPretAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret) {
            return base.Channel.addPretAsync(newPret);
        }
        
        public void updatePret(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret) {
            base.Channel.updatePret(newPret);
        }
        
        public System.Threading.Tasks.Task updatePretAsync(ClientBibliotheque.ServiceReferenceBibliotheque.Pret newPret) {
            return base.Channel.updatePretAsync(newPret);
        }
        
        public void deletePret(int id) {
            base.Channel.deletePret(id);
        }
        
        public System.Threading.Tasks.Task deletePretAsync(int id) {
            return base.Channel.deletePretAsync(id);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur getUser(string username, string password) {
            return base.Channel.getUser(username, password);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur> getUserAsync(string username, string password) {
            return base.Channel.getUserAsync(username, password);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Utilisateur[]> getUsersAsync() {
            return base.Channel.getUsersAsync();
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Categorie[] getCategories() {
            return base.Channel.getCategories();
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Categorie[]> getCategoriesAsync() {
            return base.Channel.getCategoriesAsync();
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivres() {
            return base.Channel.getLivres();
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresAsync() {
            return base.Channel.getLivresAsync();
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivresByCategorie(int categorie) {
            return base.Channel.getLivresByCategorie(categorie);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresByCategorieAsync(int categorie) {
            return base.Channel.getLivresByCategorieAsync(categorie);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[] getLivresByAuteur(int auteur) {
            return base.Channel.getLivresByAuteur(auteur);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.livreDeails[]> getLivresByAuteurAsync(int auteur) {
            return base.Channel.getLivresByAuteurAsync(auteur);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Livre getDetailsLivre(int id) {
            return base.Channel.getDetailsLivre(id);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Livre> getDetailsLivreAsync(int id) {
            return base.Channel.getDetailsLivreAsync(id);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Pret[] getPrets() {
            return base.Channel.getPrets();
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Pret[]> getPretsAsync() {
            return base.Channel.getPretsAsync();
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Auteur[] getAuteurs() {
            return base.Channel.getAuteurs();
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Auteur[]> getAuteursAsync() {
            return base.Channel.getAuteursAsync();
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Auteur getAuteur(int id) {
            return base.Channel.getAuteur(id);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Auteur> getAuteurAsync(int id) {
            return base.Channel.getAuteurAsync(id);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Categorie getCategorie(int id) {
            return base.Channel.getCategorie(id);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Categorie> getCategorieAsync(int id) {
            return base.Channel.getCategorieAsync(id);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Livre getLivre(int id) {
            return base.Channel.getLivre(id);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Livre> getLivreAsync(int id) {
            return base.Channel.getLivreAsync(id);
        }
        
        public ClientBibliotheque.ServiceReferenceBibliotheque.Pret getPret(int id) {
            return base.Channel.getPret(id);
        }
        
        public System.Threading.Tasks.Task<ClientBibliotheque.ServiceReferenceBibliotheque.Pret> getPretAsync(int id) {
            return base.Channel.getPretAsync(id);
        }
        
        public void updateRoleUser(int id, string role) {
            base.Channel.updateRoleUser(id, role);
        }
        
        public System.Threading.Tasks.Task updateRoleUserAsync(int id, string role) {
            return base.Channel.updateRoleUserAsync(id, role);
        }
    }
}
