//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auteur
    {
        public Auteur()
        {
            this.Livre = new HashSet<Livre>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string sexe { get; set; }
        public string photo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_nais { get; set; }
        public string apropos { get; set; }
        public string nationalite { get; set; }
        public string typeAuteur { get; set; }
    
        public virtual ICollection<Livre> Livre { get; set; }
    }
}
