//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBibliotheque
{
    using System;
    
    public partial class livreDeails
    {
        public int id { get; set; }
        public string titre { get; set; }
        public string resume { get; set; }
        public string isbn { get; set; }
        public string categorie { get; set; }
        public int categorieid { get; set; }
        public int auteurid { get; set; }
        public string auteur { get; set; }
        public string image { get; set; }
    }
}
