//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public Livre()
        {
            this.Pret = new HashSet<Pret>();
        }
    
        public int id { get; set; }
        public string Titre { get; set; }
        public string description { get; set; }
        public string resume { get; set; }
        public Nullable<int> quantite { get; set; }
        public string isbn { get; set; }
        public string image { get; set; }
        public Nullable<int> auteurid { get; set; }
        public Nullable<int> categorieid { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Pret> Pret { get; set; }
    }
}
