//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pret
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datedebut { get; set; }
        public Nullable<System.DateTime> datefin { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> livreid { get; set; }
    
        public virtual Livre Livre { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
