//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Pret = new HashSet<Pret>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string sexe { get; set; }
        public string photo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_nais { get; set; }
        public string nomUser { get; set; }
        public string motdepasse { get; set; }
        public string typeUser { get; set; }
        public string statusCompte { get; set; }
        public Nullable<System.DateTime> derniereconnexion { get; set; }
    
        public virtual ICollection<Pret> Pret { get; set; }
    }
}
